name: Run golint
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'

      - name: Setup GO environment
        run: |
          go mod download
          go get -u golang.org/x/lint/golint
          go get -t .

      - name: Lint
        run: |
          golint -set_exit_status ./...

      - name: Vet
        run: |
          go vet ./...
