name: Run golint
on:
#  pull_request:
#    branches:
#      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'

      - name: Setup GO environment
        run: |
          go mod download
          go get -u golang.org/x/lint/golint
          go get -t .

      - name: Lint
        id: golint
        run: |
          golint -set_exit_status ./...

      - name: Vet
        run: |
          go vet ./...
